apiVersion: v1
items:
    - apiVersion: v1
      kind: Namespace
      metadata:
        labels:
            pod-security.kubernetes.io/enforce: baseline
        name: forgejo-runners
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: keda
kind: List
