apiVersion: v1
kind: Namespace
metadata:
  name: acs-e2e-fixtures
  labels:
    app.kubernetes.io/part-of: acs-kind-e2e
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: acs-e2e-fixtures
  labels:
    app.kubernetes.io/part-of: acs-kind-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acs-e2e-registry
  template:
    metadata:
      labels:
        app: acs-e2e-registry
        app.kubernetes.io/part-of: acs-kind-e2e
    spec:
      automountServiceAccountToken: false
      containers:
        - name: registry
          image: docker.io/library/registry:2
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "2"
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: acs-e2e-fixtures
  labels:
    app.kubernetes.io/part-of: acs-kind-e2e
spec:
  type: NodePort
  selector:
    app: acs-e2e-registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
